//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Branch
{
	public virtual int branch_id
	{
		get;
		set;
	}

	public virtual string branch_address
	{
		get;
		set;
	}

	public virtual string contact_number
	{
		get;
		set;
	}

	public virtual string location
	{
		get;
		set;
	}

	public virtual void AddBranch()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveBranch()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateBranch()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetBranchInfo()
	{
		throw new System.NotImplementedException();
	}

}

