//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Cab
{
	public virtual int cab_id
	{
		get;
		set;
	}

	public virtual string type
	{
		get;
		set;
	}

	public virtual int capacity
	{
		get;
		set;
	}

	public virtual int branch_id
	{
		get;
		set;
	}

	public virtual string cab_registration_no
	{
		get;
		set;
	}

	public virtual string Status
	{
		get;
		set;
	}

	public virtual Branch Branch
	{
		get;
		set;
	}

	public virtual void CheckAvailability()
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddCab()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveCab()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateCab()
	{
		throw new System.NotImplementedException();
	}

}

