//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Client
{
	public virtual int client_id
	{
		get;
		set;
	}

	public virtual string first_name
	{
		get;
		set;
	}

	public virtual string last_name
	{
		get;
		set;
	}

	public virtual string contact_number
	{
		get;
		set;
	}

	public virtual string address_no
	{
		get;
		set;
	}

	public virtual string address_street
	{
		get;
		set;
	}

	public virtual string address_city
	{
		get;
		set;
	}

	public virtual string email
	{
		get;
		set;
	}

	public virtual void AddClient()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveClient()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateClient()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetClientInfo()
	{
		throw new System.NotImplementedException();
	}

}

