//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Employee
{
	public virtual int employee_id
	{
		get;
		set;
	}

	public virtual string first_name
	{
		get;
		set;
	}

	public virtual string nic
	{
		get;
		set;
	}

	public virtual string last_name
	{
		get;
		set;
	}

	public virtual DateTime date_of_birth
	{
		get;
		set;
	}

	public virtual string contact_number
	{
		get;
		set;
	}

	public virtual string address
	{
		get;
		set;
	}

	public virtual int branch_id
	{
		get;
		set;
	}

	public virtual string username
	{
		get;
		set;
	}

	public virtual string password
	{
		get;
		set;
	}

	public virtual string job_title
	{
		get;
		set;
	}

	public virtual Branch Branch
	{
		get;
		set;
	}

	public virtual void ChangeStatus()
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddEmployee()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateEmployee()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveEmployee()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetEmployeeInfo()
	{
		throw new System.NotImplementedException();
	}

}

