//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Package
{
	public virtual int package_id
	{
		get;
		set;
	}

	public virtual Decimal fare_per_additional_hr
	{
		get;
		set;
	}

	public virtual Decimal cost
	{
		get;
		set;
	}

	public virtual string description
	{
		get;
		set;
	}

	public virtual string package_name
	{
		get;
		set;
	}

	public virtual Decimal no_of_hrs
	{
		get;
		set;
	}

	public virtual Decimal no_of_kms
	{
		get;
		set;
	}

	public virtual Decimal fare_per_additional_km
	{
		get;
		set;
	}

	public virtual void AddPackage()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdatePackage()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemovePackage()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetPackageInfo()
	{
		throw new System.NotImplementedException();
	}

}

