//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Partner
{
	public virtual string about
	{
		get;
		set;
	}

	public virtual int partner_id
	{
		get;
		set;
	}

	public virtual string contact_number
	{
		get;
		set;
	}

	public virtual string address
	{
		get;
		set;
	}

	public virtual void AddPartner()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemovePartner()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdatePartner()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetPartnerInfo()
	{
		throw new System.NotImplementedException();
	}

}

