//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Reservation
{
	public virtual string feedback
	{
		get;
		set;
	}

	public virtual int reservation_id
	{
		get;
		set;
	}

	public virtual string pick_up_address_no
	{
		get;
		set;
	}

	public virtual string pick_up_address_street
	{
		get;
		set;
	}

	public virtual string pick_up_address_city
	{
		get;
		set;
	}

	public virtual string drop_adress_no
	{
		get;
		set;
	}

	public virtual string drop_address_street
	{
		get;
		set;
	}

	public virtual string drop_address_city
	{
		get;
		set;
	}

	public virtual DateTime pick_up_date_time
	{
		get;
		set;
	}

	public virtual DateTime drop_date_time
	{
		get;
		set;
	}

	public virtual Decimal additional_distance
	{
		get;
		set;
	}

	public virtual Decimal additional_hrs
	{
		get;
		set;
	}

	public virtual Decimal total
	{
		get;
		set;
	}

	public virtual string status
	{
		get;
		set;
	}

	public virtual int branch_id
	{
		get;
		set;
	}

	public virtual int employee_id
	{
		get;
		set;
	}

	public virtual int client_id
	{
		get;
		set;
	}

	public virtual int partner_id
	{
		get;
		set;
	}

	public virtual int package_id
	{
		get;
		set;
	}

	public virtual int cab_id
	{
		get;
		set;
	}

	public virtual Client Client
	{
		get;
		set;
	}

	public virtual Branch Branch
	{
		get;
		set;
	}

	public virtual Package Package
	{
		get;
		set;
	}

	public virtual Employee Driver
	{
		get;
		set;
	}

	public virtual Partner Partner
	{
		get;
		set;
	}

	public virtual void AddReservation()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateReservation()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveReservation()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetReservationInfo()
	{
		throw new System.NotImplementedException();
	}

}

