//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Settings
{
	public virtual string type
	{
		get;
		set;
	}

	public virtual void AddType()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveType()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateType()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetTypeInfo()
	{
		throw new System.NotImplementedException();
	}

}

